xemidev/_core/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import CustomLoginView, CustomSignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', CustomLoginView.as_view(), name='account_login'),
    path('accounts/signup/', CustomSignupView.as_view(), name='account_signup'),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('user/', include('users.urls')),
]

xemidev/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('pricing/', views.pricing, name='pricing'),
    path('terms/', views.terms, name='terms'),
    path('privacy-policy/', views.priv_pol, name='privpol'),
]

xemidev/users/urls.py
from django.urls import path
from . import views
# from .views import CustomLoginView
app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    # path('accounts/login/', CustomLoginView.as_view(), name='account_login'),
]

xemidev/projects/models.py
from django.db import models

# from users.models import User

# from techs.models import Technology

# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.category_name


class Project(models.Model):
    customer_id = models.ForeignKey('users.User', on_delete=models.RESTRICT)
    category_id = models.ForeignKey(
        'projects.Category', on_delete=models.RESTRICT)
    project_name = models.CharField(max_length=150, blank=True)
    description = models.TextField(max_length=150, blank=True)
    total_price = models.DecimalField(decimal_places=2, max_digits=4)
    start_date = models.DateField(blank=True, null=True)
    submition_date = models.DateField(blank=True, null=True)
    status = models.IntegerField(default=0)

    def __str__(self):
        return self.project_name


class SelectedTech(models.Model):
    project_id = models.ForeignKey(
        'projects.Project', on_delete=models.CASCADE)
    technology_id = models.ManyToManyField(
        'techs.Technology')

    def __str__(self):
        return f'{self.project_id} - {self.technology_id}'

xemidev/surveys/models.py
from django.db import models
# from projects.models import Category

# Create your models here.


class Question(models.Model):
    category_id = models.ForeignKey(
        'projects.Category', on_delete=models.CASCADE)
    text = models.TextField(max_length=255)

xemidev/techs/models.py
from django.db import models

# from projects.models import Question
# from projects.models import Category

# Create your models here.


class Technology(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=4)
    question_id = models.ForeignKey(
        'surveys.Question', on_delete=models.CASCADE)
    category_id = models.ForeignKey(
        'projects.Category', on_delete=models.CASCADE)

xemidev/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

# Create your models here.


class User(AbstractUser):
    """"
    Custom user model extending Django's AbstractUser.
    Includes additional fields for storing user contact details and company details.

    """

    phone_number = models.CharField(max_length=20, null=True, blank=True)
    company_name = models.CharField(max_length=100, null=True, blank=True)
    company_address = models.CharField(max_length=250, null=True, blank=True)
    company_type = models.CharField(max_length=100, null=True, blank=True)

    groups = models.ManyToManyField(
        Group,
        related_name="user_set_group",

    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="user_set_permissions",

    )

xemidev/users/forms.py
from allauth.account.forms import SignupForm
from django import forms


class SignupForm(SignupForm):
    """
    Custom form for user registration. Includes additional fields for storing user contact details.
    """
    # phone_number = forms.CharField(max_length=20)
    # company_name = forms.CharField(max_length=100)
    # company_address = forms.CharField(max_length=250)
    # company_type = forms.CharField(max_length=100)

    def save(self, request):
        user = super().save(request)
        # user.phone_number = self.cleaned_data['phone_number']
        # user.company_name = self.cleaned_data['company_name']
        # user.company_address = self.cleaned_data['company_address']
        # user.company_type = self.cleaned_data['company_type']
        user.save()
        return user

xemidev/main/views.py
from django.shortcuts import render, redirect

# Create your views here.


def home(request):
    return render(request, 'main/home.html')


def about(request):
    return render(request, 'main/about.html')


def contact(request):
    return render(request, 'main/contact.html')


def faq(request):
    return render(request, 'main/faq.html')


def pricing(request):
    return render(request, 'main/pricing.html')


def terms(request):
    return render(request, 'main/tnc.html')


def priv_pol(request):
    return render(request, 'main/priv-pol.html')

xemidev/projects/views.py
from django.shortcuts import render

# Create your views here.

xemidev/surveys/views.py
from django.shortcuts import render

# Create your views here.

xemidev/techs/views.py
from django.shortcuts import render

# Create your views here.

xemidev/users/views.py
from django.shortcuts import render
from allauth.account.views import LoginView, SignupView
# Create your views here.


def home(request):
    """
    This function renders the home page of the application.

    Parameters:
    request (HttpRequest): The request object that contains information about the current web request.

    Returns:
    HttpResponse: The rendered home page template.
    """
    return render(request, 'users/home.html')


class CustomLoginView(LoginView):  # CBV
    """
    Custom Login view
    """
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        # Add extra data to the context for the template
        context = super().get_context_data(**kwargs)
        context["extra_message"] = "Loging View from Users APP"
        return context


class CustomSignupView(SignupView):  # CBV
    """
    Custom Signup view
    """
    template_name = 'users/signup.html'

    def get_context_data(self, **kwargs):
        # Add extra data to the context for the template
        context = super().get_context_data(**kwargs)
        context["extra_message"] = "Loging View from Users APP"
        return context

xemidev/main/templates/main/about.html
{% extends "base.html" %}
{% load static %}


{% comment %} 
# Set the Title for the page 
{% endcomment %}
{% block head_title %}
About Me
{% endblock head_title %}

{% comment %} 
# Set the CSS file and Other for the page 
{% endcomment %}
{% block extra_head %}
{% endblock extra_head %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
This is about me page
{% endblock content %}

{% comment %}
# Append JS files here for the page
{% endcomment %}
{% block extra_body %}
{% endblock extra_body %}

xemidev/main/templates/main/contact.html
{% extends "base.html" %}
{% load static %}


{% comment %} 
# Set the Title for the page 
{% endcomment %}
{% block head_title %}
    Contact Information
{% endblock head_title %}

{% comment %} 
# Set the CSS file and Other for the page 
{% endcomment %}
{% block extra_head %}
{% endblock extra_head %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
    This is contact information
{% endblock content %}

{% comment %}
# Append JS files here for the page
{% endcomment %}
{% block extra_body %}
{% endblock extra_body %}

xemidev/main/templates/main/faq.html
{% extends "base.html" %}
{% load static %}


{% comment %} 
# Set the Title for the page 
{% endcomment %}
{% block head_title %}
    What da FaQ?
{% endblock head_title %}

{% comment %} 
Overrides the Default VALUES. Carefull!
{% endcomment %}
{% block extra_head %}
{% endblock extra_head %}

{% comment %}
# Set the CSS file and Other for the base page
{% endcomment %}
{% block extra_css %}
{% endblock extra_css %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
    FaQ Page
{% endblock content %}

{% comment %}
# Append JS files here for the page
{% endcomment %}
{% block extra_body %}
{% endblock extra_body %}

xemidev/main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% comment %}
# Set the Title for the page
{% endcomment %}
{% block head_title %}
  Welcome to my place
{% endblock %}

{% comment %}
# Set the CSS file and Other for the page
{% endcomment %}
{% block extra_head %}
{% endblock %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
  <section class="homesect container d-flex justify-content-center">
    <div class="d-block text-center">
      <h2 class="page-name">Red-Bazaar - Web Solutions</h2>
      <hr class="w-50 text-center mx-auto" />
      <p>We are a full-stack web development agency, specializing in building high-quality, responsive websites and mobile apps.</p>
    </div>
  </section>
  <!-- Section 2 -->
  <section class="homesect content d-flex justify-content-center">
    <div class="d-block text-center">
      <h2>Our Services</h2>
      <hr class="w-50 mx-auto"/>
      <div class="row">
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">Web Development</h3>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">Solutions for everyone</h3>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="homesect content-fluid text-center justify-content-center">
    <h2>Our Clients</h2>
    <div class="container d-flex justify-content-center">
      <div class="card">card 1</div>
      <div class="card">card 2</div>
      <div class="card">card 3</div>
    </div>
  </section>
{% endblock %}

{% comment %}
# Append JS files here for the page
{% endcomment %}
{% block extra_body %}
{% endblock %}

xemidev/main/templates/main/pricing.html
{% extends "base.html" %}
{% load static %}


{% comment %} 
# Set the Title for the page 
{% endcomment %}
{% block head_title %}
    Pricing
{% endblock head_title %}

{% comment %} 
# Set the CSS file and Other for the page 
{% endcomment %}
{% block extra_head %}
{% endblock extra_head %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
    Pricing Page
{% endblock content %}

{% comment %}
# Append JS files here for the page
{% endcomment %}
{% block extra_body %}
{% endblock extra_body %}

xemidev/main/templates/main/priv-pol.html
{% extends "base.html" %}
{% load static %}


{% comment %} 
# Set the Title for the page 
{% endcomment %}
{% block head_title %}
    Privacy Policy Information
{% endblock head_title %}

{% comment %} 
# Set the CSS file and Other for the page 
{% endcomment %}
{% block extra_head %}
{% endblock extra_head %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
    <div class="container my-5">
        <section class="text-center">
            <h1>Privacy Policy</h1>
            <p>At <strong>Red-Bazaar</strong>, accessible from <strong>red-bazaar.com</strong>, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by <strong>Red-Bazaar</strong> and how we use it.</p>
        </section>
    
        <section>
            <h2>1. Information We Collect</h2>
            <p>We collect several types of information for various purposes to provide and improve our service to you:</p>
            <ul>
                <li><strong>Personal Data:</strong> While using our site, we may ask you to provide certain personally identifiable information, such as your name, email address, and phone number, when you fill out a contact form or request a service.</li>
                <li><strong>Usage Data:</strong> We may also collect information on how the site is accessed and used, including your IP address, browser type, browser version, and the pages you visit on our site.</li>
            </ul>
        </section>
    
        <section>
            <h2>2. How We Use Your Information</h2>
            <p>We use the information we collect in the following ways:</p>
            <ul>
                <li>To provide and maintain our services.</li>
                <li>To communicate with you, such as responding to inquiries or requests.</li>
                <li>To improve our website, services, and overall user experience.</li>
                <li>To comply with legal obligations.</li>
            </ul>
        </section>
    
        <section>
            <h2>3. Cookies</h2>
            <p>We use cookies and similar tracking technologies to track activity on our site. Cookies are files with small amounts of data that may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, some parts of our site may not function properly.</p>
        </section>
    
        <section>
            <h2>4. Data Security</h2>
            <p>We are committed to ensuring that your information is secure. To prevent unauthorized access or disclosure, we have implemented appropriate physical, electronic, and managerial procedures to safeguard the information we collect online.</p>
        </section>
    
        <section>
            <h2>5. Sharing Your Information</h2>
            <p>We do not sell, trade, or otherwise transfer your Personally Identifiable Information to outside parties unless we provide you with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or serving our users, so long as those parties agree to keep this information confidential.</p>
        </section>
    
        <section>
            <h2>6. Your Data Protection Rights</h2>
            <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. These include the right to:</p>
            <ul>
                <li>Access – You have the right to request copies of your personal data.</li>
                <li>Rectification – You have the right to request that we correct any information you believe is inaccurate.</li>
                <li>Erasure – You have the right to request that we erase your personal data, under certain conditions.</li>
                <li>Restrict processing – You have the right to request that we restrict the processing of your personal data.</li>
                <li>Object to processing – You have the right to object to our processing of your personal data.</li>
                <li>Data portability – You have the right to request that we transfer the data we have collected to another organization, or directly to you, under certain conditions.</li>
            </ul>
            <p>To exercise any of these rights, please contact us using the information provided below.</p>
        </section>
    
        <section>
            <h2>7. Third-Party Links</h2>
            <p>Occasionally, at our discretion, we may include or offer third-party products or services on our website. These third-party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites.</p>
        </section>
    
        <section>
            <h2>8. Changes to This Privacy Policy</h2>
            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        </section>
    
        <section>
            <h2>9. Contact Information</h2>
            <p>If you have any questions about this Privacy Policy, please contact us:</p>
            <ul>
                <li>By email: <a href="mailto:[vgarcauk@gmail.com]">vgarcauk@gmail.com</a></li>
                <li>By visiting this page on our website: <a href="{% url "main:contact" %}">Contact Page</a></li>
            </ul>
        </section>
    </div>
{% endblock content %}

{% comment %}
# Append JS files here for the page
{% endcomment %}
{% block extra_body %}
{% endblock extra_body %}

xemidev/main/templates/main/tnc.html
{% extends "base.html" %}
{% load static %}


{% comment %} 
# Set the Title for the page 
{% endcomment %}
{% block head_title %}
    Terms and Conditions
{% endblock head_title %}

{% comment %} 
# Set the CSS file and Other for the page 
{% endcomment %}
{% block extra_head %}
{% endblock extra_head %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
    <div class="container">
        <section class="text-center my-4">
            <h2>Terms and Conditions</h2>
            <p>Welcome to my website. These Terms and Conditions govern your use of <strong>RED-BAZAAR.COM</strong> (hereinafter, the "Site"). 
                By accessing and using this Site, you agree to be bound by these terms, along with our <a href="{% url "main:privpol" %}">Privacy Policy</a>. 
                If you do not agree with these terms, please do not use this Site.</p>
        </section>

        <section>
            <h3>1. Services Offered</h3>
            <p>I am a freelance web developer offering customized web development and design services. The specific services, along with pricing and delivery timelines, will be agreed upon on an individual basis through a written contract or agreement.</p>
        </section>

        <section>
            <h3>2. Use of the Site</h3>
            <p>You are permitted to use this Site exclusively for:</p>
            <ul>
                <li>Learning about the web development services I offer.</li>
                <li>Contacting me for potential collaborations.</li>
                <li>Viewing and evaluating my portfolio projects.</li>
            </ul>
            <p>All content on this Site is protected by copyright. You may not use, copy, distribute, reproduce, or transmit any content from this Site without my prior authorization.</p>
        </section>

        <section>
            <h3>3. Projects and Deliverables</h3>
            <p>Each project will be customized according to the client's needs. The scope of work, price, and delivery timelines will be defined in a specific contract for each project. The development process will begin once both parties have agreed on the terms and conditions, and any required upfront payment has been received.</p>
        </section>

        <section>
            <h3>4. Payment Policy</h3>
            <p>Payment terms, including rates and schedules, will be specified in the project contract. Unless otherwise stated, all payments must be made on the agreed-upon dates. Payments can be made via bank transfer or other agreed methods.</p>
        </section>

        <section>
            <h3>5. Intellectual Property</h3>
            <p>All intellectual property rights related to the work I develop during a project will be transferred to the client once full payment has been made, unless otherwise stated in the contract. This includes, but is not limited to, code, design, and custom content. However, I reserve the right to display snippets or images of the project in my portfolio to promote my work, unless otherwise agreed with the client.</p>
        </section>

        <section>
            <h3>6. Use of Third-Party Services</h3>
            <p>I may use third-party tools or platforms for some projects, such as hosting, CMS, or third-party software. The use of these services will be subject to the terms and conditions of those third parties, which the client must accept.</p>
        </section>

        <section>
            <h3>7. Project Modifications and Cancellations</h3>
            <p>Any changes to the project scope after the contract has been signed must be mutually agreed upon and may be subject to a price and delivery adjustment. In the event of a project cancellation by the client, payment will be required for the work completed up to the cancellation date.</p>
        </section>

        <section>
            <h3>8. Warranty and Support</h3>
            <p>Once a project has been completed and delivered, I will offer limited support to fix bugs or issues directly related to the development of the website, as outlined in the contract. However, I am not responsible for technical issues caused by improper use of the site, third-party software errors, or modifications made by third parties without my consent.</p>
        </section>

        <section>
            <h3>9. Limitation of Liability</h3>
            <p>I am not responsible for any direct, indirect, incidental, or consequential damages that arise from the use or inability to use the Site or the services offered, even if I have been advised of the possibility of such damages.</p>
        </section>

        <section>
            <h3>10. Privacy</h3>
            <p>Your privacy is important to me. Any personal information you share while using this Site will be treated according to my <a href="[privacy-policy-link]">Privacy Policy</a>.</p>
        </section>

        <section>
            <h3>11. Changes to the Terms</h3>
            <p>I reserve the right to modify these Terms and Conditions at any time. Any changes will take effect immediately upon being posted on the Site. It is your responsibility to review these terms periodically.</p>
        </section>

        <section>
            <h3>12. Governing Law</h3>
            <p>These Terms and Conditions are governed by and interpreted in accordance with the laws of <strong>United Kingdom</strong>, without regard to its conflict of law provisions. Any dispute arising in connection with the use of the Site or the services offered will be resolved in the courts of <strong>United Kingdom</strong>.</p>
        </section>

        <section>
            <h3>13. Contact Information</h3>
            <p>If you have any questions about these Terms and Conditions, please contact me at <a href="mailto:[vgarcanuk@gmail.com]">my email</a> or use the contact form on the Site.</p>
        </section>
    </div>
{% endblock content %}

{% comment %}
# Append JS files here for the page
{% endcomment %}
{% block extra_body %}
{% endblock extra_body %}

xemidev/templates/base-templ.html
{% extends "base.html" %}
{% load static %}


{% comment %} 
# Set the Title for the page 
{% endcomment %}
{% block head_title %}
{% endblock head_title %}

{% comment %} 
# Overrides the Default VALUES. Carefull!
{% endcomment %}
{% block extra_head %}
{% endblock extra_head %}

{% comment %}
# Set the CSS file and Other for the base page
{% endcomment %}
{% block extra_css %}
{% endblock extra_css %}

{% comment %} 
# Overrides the BODY tag. Carefull!
# >>> Displayed on the template will OVERRIDES
content even if it has no information. Delete 
when not in use <<<
{% endcomment %}
{% block body %}
{% endblock body %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
{% endblock content %}

{% comment %}
# Append JS links here 
{% endcomment %}
{% block extra_body %}
{% endblock extra_body %}

{% comment %}
# Include Custom JS
{% endcomment %}
{% block custom_js %}
{% endblock custom_js %}

xemidev/templates/widgets/footer.html
<div class="container">
  <div class="row">
    <!-- About Section -->
    <div class="col-md-4">
      <h3>About Us</h3>
      <p>My mission is to simplify web development for businesses by offering custom, user-friendly solutions tailored to their needs. Whether you're looking to build a stunning new website or improve the performance of your existing one, I’m here to guide you through every step of the process and deliver results that make a difference.</p>
    </div>

    <!-- Navigation Links -->
    <div class="col-md-4">
      <div class="col">
        <h3>Quick Links</h3>
      </div>
      <div class="col d-md-flex">
        <div class="col-md-6">
          <ul class="list-unstyled">
            {# Use Django's url tag instead of Flask's url_for #}
            <li>
              <a href="{% url 'main:home' %}">Home</a>
            </li>
            <li>
              <a href="{% url 'main:about' %}">About Us</a>
            </li>
          </ul>
        </div>
        <div class="col-md-6">
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'main:faq' %}">FaQ</a>
            </li>
            <li>
              <a href="{% url 'main:terms' %}">Terms & Conditions</a>
            </li>
            <li>
              <a href="{% url 'main:privpol' %}">Privacy Policy</a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Contact Info -->
    <div class="col-md-4">
      <h3>Contact Us</h3>
      <ul class="list-unstyled">
        <li>Email: contact@example.com</li>
        <li>Phone: +1 234 567 890</li>
        <li>Address: 123 Fake Street, City, Country</li>
      </ul>
    </div>
  </div>
</div>

xemidev/templates/widgets/messages.html
{% comment %} 
    See documentation at : https://docs.djangoproject.com/en/5.1/ref/contrib/messages/
{% endcomment %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

xemidev/templates/widgets/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <!-- Logo -->
        <div class="navbar-header order-md-0">
            <h1 class="d-none">Xemolutions</h1>
            <a class="navbar-brand" href="{% url 'main:home' %}">
                <img src="{% static 'imgs/logo-01.webp' %}" width="90" height="90" alt="Main LOGO">
            </a> 
        </div>
        <!-- Toggle Button -->
        <span class="navbar-toggler order-md-3" role="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
            </svg>
        </span>
        
        <!-- Search Bar for Desktop -->
        <div class="d-flex justify-content-end d-none d-md-block order-md-2">
            <form class="form-inline d-flex flex-row-reverse" action="{% url 'main:home' %}" method="GET">
                <button class="btn btn-outline-success" type="submit">Search</button>
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            </form>
        </div>

        <!-- Navbar Links -->
        <div class="collapse navbar-collapse justify-content-center order-lg-1 order-md-4" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">MockGen</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Custom Forms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Templates</a>
                </li>
                
                {% if user.is_authenticated %}           
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
                    </li>
                    
                   
                {% else %}
                    <!-- User Login/Register Links -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Log In/Sign UP</a>
                        <ul class="dropdown-menu">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_login' %}">
                                    <i class="bi bi-caret-right-fill"> USER Login</i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_signup' %}">
                                    <i class="bi bi-caret-right-fill"> USER Registration</i>
                                </a>
                            </li>
                        </ul>
                    </li>
                    
                {% endif %}
            </ul>

            <!-- Search Bar for Mobile -->
            <div class="d-flex justify-content-center d-md-none">
                <form class="form-inline d-flex flex-row-reverse" action="{% url 'main:home' %}" method="GET">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                </form>
            </div>
        </div>
    </div>
</nav>

xemidev/users/templates/users/home.html
{% extends 'base.html' %}
{% load static %}

{% comment %}
# Set the Title for the page
{% endcomment %}
{% block head_title %}
  Welcome Users
{% endblock %}

{% comment %}
# Set the CSS file and Other for the page
{% endcomment %}
{% block extra_head %}
{% endblock %}

{% comment %}
# Appends the content in the BODY tag
{% endcomment %}
{% block content %}
  <h2>USERS page</h2>
{% endblock %}

{% comment %}
# Append JS files here for the page
{% endcomment %}
{% block extra_body %}
{% endblock %}